### ISSUE TITLE
external settings & params in config file

### ISSUE THREAD

**Issue by vaidab** [froggleston/freqtrade_analysis_notebook#3]
When you update the notebook the new version has the default values. It would be nice to have an external file with the custom modifications so that you can safely update the code while maintaining your settings.

**Comment by froggleston** [comment]
Most of the settings can be placed into the config file and they will be pulled in. What other custom modifications were you considering?

**Comment by vaidab** [comment]
The bokeh branch is actually better because most vars are set in the second cell. (Except things like db_path, pairs_to_plot, enter_tags which I find it relevant in their particular sections).
If we leave it like this, the user will have to re-add all the vars after he updates the notebook (because they don't know what sections have been updated).
Or, we can extract them all in a json file that's separate and the only location for the configuration which would make upgrading easier (and we can provide a sample config that uses real locations of directories for them, maybe based on sample_strategy).

When I checked out the code it was pretty difficult to make it work from the start, I had to do a lot of modifications, I didn't know which paths were relative and which absolute, had to figure out that the timerange for backtesting had to intersect the timerange for dry runs (else you get a division by 0 error), etc etc. 
Having a sample (external) config file would make everything work from the start and the user would build on that.

**Comment by froggleston** [comment]
The config file would still have to be understood and set by the user, and would also be another place for the configuration. I'll have to think about this, because I'd rather that everything was self-contained rather than requiring more external configurations.

**Comment by froggleston** [comment]
I've improved the second cell to include commonly used config options and the ability to override more clearly: [7d8873e](https://github.com/froggleston/freqtrade_analysis_notebook/commit/7d8873e7c75d451a3411da1c14487c066e999944)

I don't think having yet another config outside of the notebook adds any clarity, and might even make it more confusing. However, I do understand the point about what to do with updates. This is a common problem with notebooks so this would need more thought.

I don't think an external config would fix the requirement to know what the config options were or how to set them. I'd see this more of an opportunity for documentation and comments.
