### ISSUE TITLE
quick hack to keep the notebook in user_data/notebooks

### ISSUE THREAD

**Issue by vaidab** [froggleston/freqtrade_analysis_notebook#9]
Since Freqtrade already has a directory for jupyter notebooks in user_data/notebooks, I would recommend using this hack after the imports to be able to run freqtrade_analysis_notebook from that directory, instead of leaving it in the base freqtrade folder.

```
import os
os.chdir("/freqtrade/")
```

**Comment by froggleston** [comment]
The problem with this is that there's no guarantee, depending on how you've "installed" the notebook (e.g. leaving it in the cloned freqtrade_analysis_notebook directory), that the `/freqtrade/` folder exists....

**Comment by vaidab** [comment]
"Fixed" in the last patch. I've changed the cd to os.chdir + explained in comments to use /freqtrade in case of docker.

**Comment by froggleston** [comment]
Please don't close issues before any PR review or acceptance.

**Comment by froggleston** [comment]
Added support and comments for keeping the notebook and helper scripts in a cloned repo or copying to the main ft folder: [7d8873e](https://github.com/froggleston/freqtrade_analysis_notebook/commit/7d8873e7c75d451a3411da1c14487c066e999944)
